title: "Anton Hinckley â€” STAT 386 Blog"
description: "Data Curation & EDA Projects"
theme: jekyll-theme-cayman
markdown: kramdown

collections:
  posts:
    output: true
    permalink: /pokemon-stats/:path/
